name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "check"
            python: "3.11"
            toxpython: "python3.11"
            tox_env: "check"
            os: "ubuntu-latest"
          - name: "docs"
            python: "3.11"
            toxpython: "python3.11"
            tox_env: "docs"
            os: "ubuntu-latest"
          - name: "py310 (ubuntu)"
            python: "3.10"
            toxpython: "python3.10"
            python_arch: "x64"
            tox_env: "py310"
            os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.python_arch }}
      - name: install dependencies
        run: |
          python -mpip install --progress-bar=off .
          pip install tox
          pip install pytest-cov
      - name: run tests with coverage
        env:
          TOXPYTHON: "${{ matrix.toxpython }}"
        run: |
          tox -e ${{ matrix.tox_env }} -- --cov=.
      - name: generate coverage report
        if: matrix.name == 'py310 (ubuntu)'
        run: |
          pytest --cov=./ --cov-report xml:coverage.xml
      - name: upload coverage report
        if: matrix.name == 'py310 (ubuntu)'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  upload-coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Ensure your CODECOV_TOKEN is set in GitHub Secrets
          files: coverage.xml
          name: codecov-umbrella  # Optional: Name for the upload to distinguish it in the UI
